name: nightly-tests
on: [push, pull_request]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy Robot
        uses: actions/checkout@v4
        with:
          path: robot
          persist-credentials: false

      - name: Run Tests
        run: |
          docker run --rm -v `pwd`/robot:/robot unifyai/robot:latest python3 -m pytest ivy_robot_tests/
